apiVersion: v1
kind: Pod
metadata:
    name: pod-2
    label:
        app: segundo-pod
spec:
    containers:
        - name: container-pod-2
          image: nginx:latest
          ports:
            - containerPort: 80